replicaCount: 1
service:
  type: LoadBalancer

bucket-resource:
  prefix: bucket
  suffix: resource
  names: ["one", "two", "three"]
  syncwave: "-10" # prior to any resources lacking annotation

database-resource:
  prefix: database
  suffix: resource
  names: ["one", "two", "three"]
  syncwave: "-20" # prior to any resources lacking annotation
